### ISSUE TITLE
SSR shader authoring

### ISSUE THREAD

**Issue by ImanolFotia** [JoeyDeVries/Cell#7]
Hello Joey, I see that you are using my [Screen Space Reflections](http://imanolfotia.com/blog/update/2017/03/11/ScreenSpaceReflections.html) shader implementation, I'm glad that you found it useful, and I'm ok with you using it without any changes to my original code as shown [here](https://gist.github.com/ImanolFotia/57882ae1f23e5076b1ab498253175366) and [here](http://imanolfotia.com/blog/update/2017/03/11/ScreenSpaceReflections.html), but I would also like to see a link or some kind of credits to the original author inside the shader, since it's licensed under GNU General Public License v3.0

Greetings

**Comment by JoeyDeVries** [comment]
Definitely! And my apologies. I've included SSR as an experiment, but I had a bit too many issues getting it to render consistently across a variety of different scenes, so I decided not to pursue it much further. I was therefore a bit lazy with authoring. I've removed the code from Cell, but I definitely should've mentioned you right from the start, thank you for letting me know; and thank you for the writeup! :)
